# This file tells GitLab how to build and deploy your site
image: node:20-bookworm

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv dist public  # GitLab Pages requires the folder to be named 'public'
  artifacts:
    paths:
      - public
  only:
    - main # Only deploys when you push to the main branch